// ===== ACHIEVEMENT DEFINITIONS =====
export const ACHIEVEMENTS = [
    { id: 'first_blood', name: 'First Blood', desc: 'Kill your first enemy', icon: '\u{1F5E1}', check: s => s.totalKills >= 1 },
    { id: 'wave10', name: 'Holding Strong', desc: 'Survive 10 waves', icon: '\u{1F6E1}', check: s => s.wavesCompleted >= 10 },
    { id: 'wave30', name: 'Veteran Defender', desc: 'Survive 30 waves', icon: '\u{1F3C5}', check: s => s.wavesCompleted >= 30 },
    { id: 'rich', name: 'War Chest', desc: 'Have 1000 gold at once', icon: '\u{1F4B0}', check: s => s.maxGold >= 1000 },
    { id: 'mythic_tower', name: 'Mythic Guardian', desc: 'Get a tower to Mythic mastery', icon: '\u{1F48E}', check: s => s.maxMastery >= 500 },
    { id: 'tier5', name: 'Ultimate Power', desc: 'Upgrade a tower to Tier 5', icon: '\u{2B50}', check: s => s.maxTier >= 5 },
    { id: 'no_leak', name: 'Perfect Defense', desc: 'Complete a map with no leaks', icon: '\u{1F31F}', check: s => s.perfectWaves > 0 },
    { id: 'kills100', name: 'Centurion', desc: 'Kill 100 enemies in one game', icon: '\u{1F5E1}', check: s => s.totalKills >= 100 },
    { id: 'kills500', name: 'Slayer', desc: 'Kill 500 enemies in one game', icon: '\u{2694}', check: s => s.totalKills >= 500 },
    { id: 'map1', name: 'Valley Victor', desc: 'Complete Green Valley', icon: '\u{1F332}', check: s => s.mapsCompleted?.includes(0) },
    { id: 'map2', name: 'Desert Storm', desc: 'Complete Desert Pass', icon: '\u{1F3DC}', check: s => s.mapsCompleted?.includes(1) },
    { id: 'map3', name: 'Ice Breaker', desc: 'Complete Frozen Peak', icon: '\u{2744}', check: s => s.mapsCompleted?.includes(2) },
    { id: 'map4', name: 'Fire Walker', desc: 'Complete Volcanic Rift', icon: '\u{1F30B}', check: s => s.mapsCompleted?.includes(3) },
    { id: 'map5', name: 'Shadow Lord', desc: 'Complete Shadow Realm', icon: '\u{1F47B}', check: s => s.mapsCompleted?.includes(4) },
    { id: 'towers8', name: 'Arsenal', desc: 'Build all 8 tower types in one game', icon: '\u{1F3F0}', check: s => s.towerTypesBuilt >= 8 },
    { id: 'speed3', name: 'Fast Forward', desc: 'Play at 3x speed', icon: '\u{23E9}', check: s => s.usedSpeed3 },
    { id: 'boss5', name: 'Boss Hunter', desc: 'Kill 5 bosses in one game', icon: '\u{1F479}', check: s => s.bossKills >= 5 },
    { id: 'combo8', name: 'Tower Army', desc: 'Get 8 towers of same type combo', icon: '\u{1F3AF}', check: s => s.maxCombo >= 8 },
    { id: 'research5', name: 'Researcher', desc: 'Unlock 5 research nodes', icon: '\u{1F52C}', check: s => s.researchCount >= 5 },
    { id: 'all_maps', name: 'Conqueror', desc: 'Complete all 5 maps', icon: '\u{1F451}', check: s => (s.mapsCompleted?.length || 0) >= 5 },

    // New achievements
    { id: 'kills1000', name: 'Annihilator', desc: 'Kill 1000 enemies in one game', icon: '\u{1F480}', check: s => s.totalKills >= 1000 },
    { id: 'kills5000', name: 'Extinction Event', desc: 'Kill 5000 enemies in one game', icon: '\u{2622}', check: s => s.totalKills >= 5000 },
    { id: 'wave50', name: 'Unbreakable Wall', desc: 'Survive 50 waves', icon: '\u{1F3F0}', check: s => s.wavesCompleted >= 50 },
    { id: 'gold5000', name: 'Dragon Hoard', desc: 'Have 5000 gold at once', icon: '\u{1F4B0}', check: s => s.maxGold >= 5000 },
    { id: 'boss20', name: 'Boss Slayer', desc: 'Kill 20 bosses in one game', icon: '\u{1F47E}', check: s => s.bossKills >= 20 },
    { id: 'overclock10', name: 'Overclocker', desc: 'Overclock towers 10 times in one game', icon: '\u{2699}', check: s => s.overclockCount >= 10 },
    { id: 'no_tower_lost', name: 'Zero Casualties', desc: 'Complete a map without selling any tower', icon: '\u{1F3C6}', check: s => s.towersNeverSold },
    { id: 'speed_run', name: 'Speed Demon', desc: 'Complete a map in under 10 minutes', icon: '\u{23F1}', check: s => s.fastestClear < 600 },
    { id: 'full_research', name: 'Research Complete', desc: 'Unlock all research nodes', icon: '\u{1F9EA}', check: s => s.researchCount >= 30 },
    { id: 'multi_tier5', name: 'Tower of Power', desc: 'Have 3 Tier 5 towers at once', icon: '\u{1F31F}', check: s => s.tier5Count >= 3 },
    { id: 'first_ability', name: 'Ability Unlocked', desc: 'Use an ability for the first time', icon: '\u{2728}', check: s => s.abilitiesUsed >= 1 },
    { id: 'synergy_master', name: 'Synergy Master', desc: 'Activate 5 different synergy types', icon: '\u{1F91D}', check: s => s.synergyTypesActivated >= 5 },
];
